name: Build&Run server

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag nstu_abitur && \
            docker run -d -p 5000:5000 -e PORT=5000 nstu_abitur